package sop_corba;


/**
* sop_corba/FacturaIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from factura.idl
* lunes 3 de julio de 2023 06:05:36 PM COT
*/

public interface FacturaIntOperations 
{
  boolean generarFactura (sop_corba.FacturaIntPackage.facturaDTO datos);
} // interface FacturaIntOperations
