package sop_corba;


/**
* sop_corba/OfertasIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from oferta.idl
* lunes 3 de julio de 2023 12:00:46 PM COT
*/

public interface OfertasIntOperations 
{
  float[] obtenerOfertas ();
} // interface OfertasIntOperations
