package sop_corba;

/**
* sop_corba/OfertasIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from oferta.idl
* lunes 3 de julio de 2023 12:00:46 PM COT
*/

public final class OfertasIntHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.OfertasInt value = null;

  public OfertasIntHolder ()
  {
  }

  public OfertasIntHolder (sop_corba.OfertasInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.OfertasIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.OfertasIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.OfertasIntHelper.type ();
  }

}
