package sop_corba;


/**
* sop_corba/OfertasInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from oferta.idl
* lunes 3 de julio de 2023 12:00:46 PM COT
*/

public interface OfertasInt extends OfertasIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface OfertasInt
