package sop_corba.OfertasIntPackage;


/**
* sop_corba/OfertasIntPackage/listaOfertasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from oferta.idl
* lunes 3 de julio de 2023 12:00:46 PM COT
*/

public final class listaOfertasHolder implements org.omg.CORBA.portable.Streamable
{
  public float value[] = null;

  public listaOfertasHolder ()
  {
  }

  public listaOfertasHolder (float[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.OfertasIntPackage.listaOfertasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.OfertasIntPackage.listaOfertasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.OfertasIntPackage.listaOfertasHelper.type ();
  }

}
